### ISSUE TITLE
The plotted visual cost matrix is wrong, isn't it?

### ISSUE THREAD

**Issue by lunzueta** [VSainteuf/metric-guided-prototypes-pytorch#2]
Shouldn't it be seq = [7,1,4,0,9,6,8,3,5,2] instead of seq = [2,5,3,8,6,9,0,4,1,7]? This way it would be like in the paper.

**Comment by VSainteuf** [comment]
Hi @lunzueta ,
Yes good catch! Indeed I entered the labels of the figure in reverse order by mistake, I'll fix this.

**Comment by lunzueta** [comment]
Sorry, I think I said it wrong. The matrix is not correctly plotted, but it is because instead of `plt.imshow(D_vis[seq[::-1],:][:,seq[::-1]])`  it should be `plt.imshow(D_vis[seq,:][:,seq])`. Then, it would look like this (coherent with the paper's hierarchy):

![imagen](https://user-images.githubusercontent.com/4266279/145539975-e30b5460-54ba-4a0e-a1fd-a1a055b2ea6b.png)
